
services:
  - type: web
    name: rezonanta-gpt-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
